### ISSUE TITLE
PR[#126] case error: '-Wno-error=infinite-recursion': no option '-Winfinite-recursion'

### ISSUE THREAD

**Issue by betnevs** [mit-pdos/xv6-riscv#130]
add `-Wno-error=infinite-recursion` in Makefile cause error: '-Wno-error=infinite-recursion': no option '-Winfinite-recursion', remoeve `-Wno-error=infinite-recursion` then everything works well.

**Comment by sora-blue** [comment]
It also happened to me. I think the problem lies in the version of GCC.
According to [this post](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=88232), the flag is **implemented in GCC 12**,
while gcc [here](https://github.com/riscv/riscv-gnu-toolchain) maybe a little out of date.
For me, it is `riscv-gcc-10.2.0`

PS: According to [issue #125 ], the problem occurs in GCC 11.  So the commit switched to GCC 11.

**Comment by dinarior** [comment]
https://github.com/mit-pdos/xv6-riscv/pull/126

Breaks compilation for all gcc versions prior to 12.

**Comment by faisalmuhabi** [comment]
How do you remove the recursion?

**Comment by sora-blue** [comment]
@faisalmuhabi Perhaps earlier version of GCC won't treat it as a compile-time error.

**Comment by trizyal** [comment]
I had this issue, for the short term, I have fixed this by reverting my makefile to before the latest commit and it works perfectly. If somebody else needs to use this urgently (like I need to because I had a coursework based on this, and this coursework was assigned before the commit), they can do the same.

**Comment by kaashoek** [comment]
Sorry for breaking xv6 when compiling with gcc version < 12.   I believe I fixed the source code (reverting the Makefile change and changing sh.c) so that it compiles correctly now with gcc 12 and earlier versions (i tried gcc 10 and 12).
